name: Maven Verify
on:
  push:
    branches:
      - "master"
      - "main"
  pull_request:
    types: [ opened, synchronize, reopened ]
  workflow_dispatch:

jobs:
  mvn-verify:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
          architecture: x64
          cache: maven
      - name: Maven Verify
        run: mvn --batch-mode --update-snapshots verify
